# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [2]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [42]:
# Your code here
my_list = [3, 7, 14, 18, 19, 24]
my_arr = np.array([3, 7, 14, 18, 19, 24])

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [22]:
# Your code here
my_list *= 4
my_arr *= 4
#the items in list will be printed over 4 times and the items in the array will each be multiplied by 4
print(my_list)
print(my_arr)

[3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24]
[12 28 56 72 76 96]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [26]:
# Your code here
my_list += my_list
my_arr += my_arr
print(my_list)
print(my_arr)
# all the items in my_list are added to the end of my_list but for my_arr all the coresponding items are added. 

[3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24]
[ 48 112 224 288 304 384]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [34]:
# Your code here
# my_list -= my_list
my_arr -= my_arr
print(my_list)
print(my_arr)
#subtracting my_list from my_list returns an error becuase it removes all values from the list and the computer doesn't like that. 
#For subtracting my_arr from my_arr, an array of 0's is returned. 

[3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24, 3, 7, 14, 18, 19, 24]
[0 0 0 0 0 0]


5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [54]:
# Your code here
# my_list *= my_list
my_arr *= my_arr
print(my_list)
print(my_arr)
#first I reran the cell initializing my_arr and my_list so I had numbers to work with. Multiplying two lists does not work but 
#multiplying two arrays will return an array of the same size with each item multiplied by itself

[3, 7, 14, 18, 19, 24]
[    81   2401  38416 104976 130321 331776]


7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [74]:
# Your code here
#my_list = my_list / my_list
my_arr = my_arr / my_arr
print(my_list)
print(my_arr)
#division didn't work with the lists but did work with the array where it divied each coresponding item. However, '/=' did not work 
#and I had explicitly write out the division.

[3, 7, 14, 18, 19, 24]
[1. 1. 1. 1. 1. 1.]


8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

# Your code here
A list does not require a package and is already integrated in python, however it is not great for doing math and is more difficult to change the values of each item. An array comes from the numpy package which has to be imported first. Arrays are better for doing math because the opperation will be applied to each seperate item while for lists it more so manipulates the lenght of the list rather than its individual items. 

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [270]:
# Your code here
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
def second_value(arr2D):
#returns the second value for each row in the array
    second_values = arr2D[0:len(arr2D), 1]
    return second_values

print(second_value(arr3))

[ 4 10 16]


In 2-3 sentences, describe what section of the website helped you write your function. 

# Your comment here
I went to the slicing array section of the website. There I saw examples showing how to access and return certain elements of arrays of various lengths. This is where I found out how to set a range to access elements. 

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

In [264]:
#To access the second value of each row in a nested list you would need to loop through each element in each row. 
#This would take two for statements, the first one looping though the rows and the second one looping though the elements. 

nested_list = [[1, 2, 3], [4, 5, 6]]
def second_value_nested_loop(list):
#returns the second value of each row in a list
    second_values = []
    for i in range(len(list)):
        for j in range(len(list[i])):
            if j == 1:
                second_values.append(list[i][j])

    return second_values
second_value_nested_loop(nested_list)

[2, 5]

## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [349]:
# Your code here
#themed after array interation 
apple_tree = np.array([['leaf', 'leaf', 'apple', 'leaf'],['apple', 'apple', 'leaf', 'leaf'], ['leaf', 'apple', 'leaf', 'leaf'],
                      ['leaf', 'leaf', 'apple', 'apple']])
def apple_picking(tree_arr):
# takes an apple tree array, and picks out the apples from the leaves. returns how many apples were picked from that apple tree array
    basket = np.array([])
    for i in tree_arr: #looping though rows
        for j in i: # looping though elements of each row
            if  j == 'apple': #checking if element is an apple
                basket = np.append(basket, j) #adding apple to basket 
    message = (f'You have {len(basket)} apples in your basket')

    return message

apple_picking(apple_tree)

'You have 6 apples in your basket'

In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [351]:
# Your code here
#Iterating Arrays
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

#Iterating 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
#for all rows
for x in arr:
  print(x)
#scalar iteration
for x in arr:
  for y in x:
    print(y)

#Iterating 3D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)
#scalar iteration
for x in arr:
  for y in x:
    for z in y:
      print(z)

#Iterating Arryas using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

#Iterating with different data types
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

#Iterating with different step size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

#Enumerated iteration using ndenumerate()
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'
1
3
5
7
(0,) 1
(1,) 2
(2,) 3


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

# Your comment here
The NumPy Array Iterating section went over how to loop though the elements of arrays, including arrays of more than one dimension and arrays with non-integer elements. This inspired me to write a function that took a 2D arr and looped though each row and element. To make it more comlicated I was also partially inspired by the Array Search section which was manifested in the search for apples. 

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [396]:
# Your code here
import even_sum

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [418]:
# Your code here
my_list = [7, 3, 4, 8, 5, 6, 9]
print(even_sum.sum_even_numbers(my_list))

AttributeError: module 'even_sum' has no attribute 'sum_even_numbers'

I have provided you a separate module called `example.py`. Import that module here.

In [384]:
# Your code here
import example

With the following variables, use my module to show which of the rocket's escape!

In [386]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [406]:
# Your code here
example.escape_velocity(mass_of_planet, radius_of_planet)
example.orbital_velocity(mass_of_planet, radius_of_planet)
example.rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet)

['Rocket left the planet!',
 'Rocket is orbiting around the planet.',
 'Rocket crashes back into the planet!']

In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

# Your comments here
This code follows "good coding practices" by naming functions and variables explicitly so you can clearly tell what they are and what they do. The code also has a lot of comments that describe what the inputs, outputs, and what each function is doing. An improvement that could be made is naming the module something other than example so that you know what the module does. 

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [682]:
gain = np.array([[4,7,8],[1,2,4],[8,9,11]])
loss = np.array([[3,2,1],[20, 23, 24],[5,4,2]])


print(heating_rate(gain))
print(energy_lost_rate(loss))
achieve(gain, loss)
    

[6.33333333 2.33333333 9.33333333]
[ 2.         22.33333333  3.66666667]
[  4.33333333 -20.           5.66666667]
run 0 achieved ignition
run 1 did not reach ignition
run 2 achieved ignition


In [684]:
# Your comment here

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [715]:
# Your comment here

Once your module is complete, import it here.

In [793]:
# Your code here
import ignition

Call each of your functions in the cell below. Make sure to show the outputs! 

In [797]:
# Your code here
gain = np.array([[4,7,8],[1,2,4],[8,9,11]])
loss = np.array([[3,2,1],[20, 23, 24],[5,4,2]])

print(ignition.heating_rate(gain))
print(ignition.energy_lost_rate(loss))
ignition.achieve(gain, loss)

[ 6.33333333  8.66666667 18.        ]
[ 2.         24.33333333 28.        ]
run 0 achieved ignition
run 1 did not reach ignition
run 2 did not reach ignition


# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!